#!/usr/bin/env python3
"""
Macro Market Update - Main Orchestrator (Curated Edition)
Fetches data, renders PNG, optionally posts to Discord.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

# Load .env if present
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from fetch_market_data import fetch_all_data, build_report, save_json
from render_table import render_market_update
from datetime import datetime
import argparse


# ─── Caption generation (LLM-powered, fresh every day) ──────────────────────
# The caption is generated by poolside/laguna-s-2.1:free via OpenRouter,
# using today's actual market data as context.  See llm_utils.py.
from llm_utils import generate_caption as _llm_generate_caption


def generate_caption(rows: list) -> str:
    """Generate a fresh, LLM-powered caption from the report rows."""
    return _llm_generate_caption(rows)


def run_pipeline(post_to_discord: bool = False, discord_webhook: str = None, date_str: str = None):
    """Run the full pipeline: fetch → render → (optionally post)."""
    # Check env for webhook if not provided
    if discord_webhook is None:
        discord_webhook = os.getenv("DISCORD_WEBHOOK_URL")

    print(f"\n{'='*60}")
    print(f"MACRO MARKET UPDATE PIPELINE (Curated)")
    print(f"{'='*60}")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # 1. Fetch data
    print("\n[1/3] Fetching market data...")
    data = fetch_all_data()

    # 2. Build report
    print("\n[2/3] Building report with fresh narratives...")
    rows, timestamp = build_report(data)
    save_json(data, rows, timestamp)

    # Generate caption
    caption = generate_caption(rows)
    print(f"\n[Caption] {caption}")

    # Render PNG
    print("\n[3/3] Rendering PNG...")
    if date_str is None:
        date_str = datetime.now().strftime("%Y%m%d")
    png_path = render_market_update({"timestamp": timestamp, "rows": rows}, date_str=date_str)

    # Save caption sidecar for the web dashboard
    caption_path = os.path.join("output", f"market_caption_{date_str}.txt")
    with open(caption_path, "w") as f:
        f.write(caption)

    # Copy latest PNG + JSON + caption into static/ so GitHub Pages and the
    # API can serve the most recent snapshot alongside 13F data
    static_dir = os.path.join(
        os.environ.get("USERPROFILE", os.path.expanduser("~")),
        "13f-scanner-web", "static",
    )
    snapshots_web_dir = os.path.join(static_dir, "snapshots")
    os.makedirs(snapshots_web_dir, exist_ok=True)
    import shutil
    shutil.copy2(png_path, os.path.join(snapshots_web_dir, "market_snapshot.png"))
    latest_json = f"output/market_report_{date_str}.json"
    if os.path.exists(latest_json):
        shutil.copy2(latest_json, os.path.join(snapshots_web_dir, "market_report_latest.json"))
    shutil.copy2(caption_path, os.path.join(snapshots_web_dir, "market_caption_latest.txt"))

    print(f"\n{'='*60}")
    print(f"COMPLETE: {png_path}")
    print(f"{'='*60}\n")

    # 4. Optional: Post to Discord via webhook
    if post_to_discord and discord_webhook:
        post_to_discord_webhook(png_path, timestamp, discord_webhook, caption)
    elif post_to_discord and not discord_webhook:
        print("[Discord] ⚠️  No webhook URL provided (set DISCORD_WEBHOOK_URL env var or --discord-webhook)")

    return png_path


def post_to_discord_webhook(image_path: str, timestamp: str, webhook_url: str, caption: str = ""):
    """Post the PNG to Discord via webhook."""
    import requests

    print(f"\n[Discord] Posting to webhook...")
    try:
        with open(image_path, 'rb') as f:
            files = {'file': (os.path.basename(image_path), f, 'image/png')}
            content = f"Macro Market Update — {timestamp}"
            if caption:
                content = f"{caption}\n\n{content}"
            data = {
                'content': content
            }
            response = requests.post(webhook_url, files=files, data=data, timeout=30)
            response.raise_for_status()
            print(f"[Discord] ✅ Posted successfully")
    except Exception as e:
        print(f"[Discord] ❌ Failed: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate daily macro market update (curated)")
    parser.add_argument("--date", help="Date string (YYYYMMDD), defaults to today")
    parser.add_argument("--discord-webhook", help="Discord webhook URL to post result")
    parser.add_argument("--post-discord", action="store_true", help="Post to Discord (requires --discord-webhook)")

    args = parser.parse_args()

    run_pipeline(
        post_to_discord=args.post_discord,
        discord_webhook=args.discord_webhook,
        date_str=args.date
    )